### ISSUE TITLE
Windows 11: Ampersand "&" is tripled in tray notification

### ISSUE THREAD

**Issue by DarkVoyage** [reupen/columns_ui#1010]
![image](https://github.com/user-attachments/assets/bf743025-a22c-48cd-a03b-c385d083b34b)

**Comment by reupen** [comment]
Unfortunately, it's a Windows 11 bug, as the tooltips have always displayed correctly on older versions of Windows. I already reported it on the Feedback Hub some time ago and I've only just noticed that they've given a reply saying that they can't reproduce it...

https://aka.ms/AAjwm3y

I suggest reporting it on the Feedback Hub again.

**Comment by DarkVoyage** [comment]
Thanks for info. Then this is dead end.

**Comment by reupen** [comment]
Will keep this open to acknowledge that the problem exists and for anyone else that comes along to report it.
