### ISSUE TITLE
(dev build) Item details: $rgb does not always work

### ISSUE THREAD

**Issue by Nojevah** [reupen/columns_ui#1036]
I just tried dev build foo_ui_columns-2.1.0+308.gbe15304.github.r12361785837.1568.x64 (Windows 11)

Compared to 2.1.0 stable build, this code works differently in Item Details:

$set_font(Consolas,15,)
$rgb(255,0,0)%playback_time%
$crlf()
$rgb(0,128,255)[%length%]
$crlf()
$set_font(Consolas,13,)

%length% color is not applied.

If I remove $set_font(Consolas,13,), it works.
Or I can add $rgb() after [%length%]:
$rgb(0,128,255)[%length%]$rgb()

**Comment by reupen** [comment]
Hi,

Thanks for the report. Could you try the build attached to https://github.com/reupen/columns_ui/actions/runs/12382050854?pr=1037?

**Comment by Nojevah** [comment]
Confirmed fixed, that was fast !
