### ISSUE TITLE
Add ability to control look-and-feel of scrollbars

### ISSUE THREAD

**Issue by mrandreastoth** [reupen/columns_ui#132]
Please add the ability to control the look-and-feel of scrollbars, i.e., colours, width, etc., etc.

**Comment by reupen** [comment]
Hi,

I'm afraid the scroll bars come from the operating system and customising them is not simple. Hence, there is no plan to add any such feature.

Your best bet would be to look into using a custom Windows theme.

Thanks

**Comment by reupen** [comment]
It could, I'm just being realistic in saying that it's not a priority. The existing scroll bars are closely linked with how the panels work and JScript panel is quite different in how it works.
