### ISSUE TITLE
Item properties column field truncated

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#138]
Just a small thing. In Item properties the Field column is a little bit to small, so that many fields are truncated. 
![two elegies for violin and piano_ i andantino - pettersson - duo gelland _2018-08-15_14-15-24](https://user-images.githubusercontent.com/15456836/44147900-50b3b5fc-a096-11e8-8021-091788602594.png)

**Comment by grimes2** [comment]
Thanks, you are right.
![foobar2000_2018-08-15_20-04-59](https://user-images.githubusercontent.com/15456836/44164608-cbebd800-a0c6-11e8-8ccd-375d412cac06.png)

**Comment by stephen147** [comment]
> Hi,
> 
> I will have a look at the defaults (there may be a DPI-related problem with them). However, you can right-click on the panel and turn off 'Auto-sizing columns' and resize the columns. The column sizes should survive a restart.

I came here to report something similar.

## If I uncheck the resize columns, it's truncating the value column on the right where the red line is.
![image](https://user-images.githubusercontent.com/14054664/79474837-d62e4a00-7ffe-11ea-9804-dea7fd49db39.png)

## Here's if that is enabled, you can see the left column is cut off.
![image](https://user-images.githubusercontent.com/14054664/79474954-fb22bd00-7ffe-11ea-9bfa-36946343d33d.png)

**Comment by reupen** [comment]
You should be able to resolve that in the same way:

1. Turn on column titles
1. Turn off auto-size columns
1. Resize the first column
1. Change the auto-size and show column titles settings back
