### ISSUE TITLE
Foobar hang after press Tab key

### ISSUE THREAD

**Issue by infectormp** [reupen/columns_ui#148]
Foobar hang after press Tab key
![foobar](https://user-images.githubusercontent.com/9958813/49689184-93b54d00-fb2e-11e8-94fe-1e53c7b7e673.gif)

Foobar 1.4.1
Columns UI 1.0.0-beta.1

With classic UI all fine

**Comment by reupen** [comment]
Thanks. It's related to another bug that was reported (Tab not stopping on the playlist view), but it shouldn't get stuck in an infinite loop like that either.
