### ISSUE TITLE
Use DirectWrite to render text

### ISSUE THREAD

**Issue by reupen** [reupen/columns_ui#15]
If possible.

See also colour fonts: https://docs.microsoft.com/en-us/windows/win32/directwrite/color-fonts

**Comment by razielanarki** [comment]
Hi!

i've implemented a win7 compatible GDI dwrite renderer (color fonts/emoji support), finetuned to be gdi text-metrics compatible, in my fork of foo_spider_monkey_panel, however i'm currently refactoring / breaking up my branch it's on, but still, the sources could be useful for refrerence: 
- implementation: 
   [utils/dwrite_renderer.cpp](https://github.com/razielanarki/foo_spider_monkey_panel/blob/feature/gdi_graphics_and_theme_manager_api_extensions_and_fixes/foo_spider_monkey_panel/utils/dwrite_renderer.cpp) + [utils/dwrite_renderer.h](https://github.com/razielanarki/foo_spider_monkey_panel/blob/feature/gdi_graphics_and_theme_manager_api_extensions_and_fixes/foo_spider_monkey_panel/utils/dwrite_renderer.h)
- usage examples (a try at GDI and a GDI+ compatible wrapper call): 
   [js_objects/gdi_graphics.cpp#L1329-L1602](https://github.com/razielanarki/foo_spider_monkey_panel/blob/674a01f006e748a8c8b1bdc1f8a39dccf2b51862/foo_spider_monkey_panel/js_objects/gdi_graphics.cpp#L1329-L1602 )   (warning: horrendously long functions, in dire need of refactoring)

**Comment by reupen** [comment]
Thanks, that could be useful when I get to this 😄

**Comment by JWatersMeet** [comment]
+1 for this, for the color emoji support. I increasingly see these used in song titles.

**Comment by reupen** [comment]
Closing in favour of some new, more specific tickets now progress has been made: https://github.com/reupen/columns_ui/issues?q=is%3Aissue+is%3Aopen+label%3Adirectwrite
