### ISSUE TITLE
Layout and Filter tabs disappeared in Columns UI 1.0.0

### ISSUE THREAD

**Issue by chronoxor** [reupen/columns_ui#162]
Layout and Filter tabs disappeared in Columns UI 1.0.0. As the result I lost ability to setup filters filed order - it is vital to have "Artist;Album Artist" filter order for my media library!

Columns UI 0.3.8.8:
![image](https://user-images.githubusercontent.com/4397805/53686614-731a1f00-3d3a-11e9-84fa-21a2d96b25ff.png)

Columns UI 1.0.0:
![image](https://user-images.githubusercontent.com/4397805/53686631-b83e5100-3d3a-11e9-8ef6-df914172cb03.png)

**Comment by reupen** [comment]
The settings have just been reorganised. Click on the > symbol next to Columns UI in the tree on the left-hand side and the other pages will listed underneath,

**Comment by chronoxor** [comment]
Thanks a lot! Finally managed to found required settings.

![image](https://user-images.githubusercontent.com/4397805/53694187-56bec680-3dbc-11e9-89b1-8171af42199a.png)
