### ISSUE TITLE
Choose sorting direction when auto-send to playlist

### ISSUE THREAD

**Issue by OdinGitDat** [reupen/columns_ui#171]
It's nice that we can have a custom sort script when auto-sending a filter selection to playlist, but I would also like to choose the direction of the order (descending vs ascending).

**Comment by reupen** [comment]
Could you give an example of what you'd use it for?

**Comment by OdinGitDat** [comment]
When I select an artist in the filter I would like all their album's to be sorted by most recently released in the playlist. Currently I achieve something close with `$sub(9999,%date%)` but for most albums only the release year is available, not exact date. So _within_ each year the order is still reversed (example in pic below).

Personally, I have catalogue numbers tagged on my music, so if I could sort in descending order by those it will work (or even by album title descending in the case below).

I realize this is a very niche use-case, but it's something that I'd love to have.

![](https://dl.dropboxusercontent.com/s/cgq6ukwof8fmja3/foobar2000_2019-04-07_15-18-27.png)

**Comment by reupen** [comment]
Thanks, that makes sense.
