### ISSUE TITLE
Automatically cyclically scroll column content in view to display overlong content

### ISSUE THREAD

**Issue by mzso** [reupen/columns_ui#178]
I think cyclically scrolling content back-and forth (or just forth) when they're too long would make sense. I saw this method used sometimes, for example with TV EGP views.

I thought of this when looking at the the column I have for codec. Most of them are typically short 3-6 characters. Then there are horrors like "Microsoft ADPCM".
But other fields could have use of this. Titles or performers sometimes can get overly long. With no good way to view them, only opening the properties and looking for the respective metadata field.

**Comment by reupen** [comment]
As this refers to columns, I assume this is referring to the playlist view. I don't see having columns of scrolling content as being particularly pleasant, sorry. Also, tooltips are available for truncated content.

Let me know if I've misunderstood.
