### ISSUE TITLE
Can't change the font size

### ISSUE THREAD

**Issue by whills1138** [reupen/columns_ui#223]
In preference menu, I tried to change the fonts, but I can only change the font type. I clicked different font size, but it always shows '0pt' and the font size didn't change at all. I think it's a bug. (v1.2.0-rc1)
![Snipaste_2019-08-30_10-58-54](https://user-images.githubusercontent.com/54695895/63990061-2c548880-cb15-11e9-8db7-634d10af34c3.jpg)
[EDIT] v1.0.0 doesn't have this problem

**Comment by reupen** [comment]
Unfortunately, this is caused by foo\_ui\_hacks. Please remove it if you have it installed.

**Comment by whills1138** [comment]
> Unfortunately, this is caused by foo_ui_hacks. Please remove it if you have it installed.

Thank you for your information.
