### ISSUE TITLE
Filter panels: Add a search field that refines what is shown in CUI Filter panels based on query syntax

### ISSUE THREAD

**Issue by Daeron08** [reupen/columns_ui#27]
A search field that accepts query syntax and filters the results shown in CUI Filter panels. 

Suppose you input '"$info(encoding)" IS lossless' into the search field, All existing CUI Filter panels would only show lossless files but would function as normal otherwise.

The search field would most likely be better off being a separate UI element as opposed to Facets' fixed toolbar up top.

A more advanced version could support saving favorite queries and using multiple queries at once (toggle-able buttons each corresponding to a saved query perhaps?).

**Comment by reupen** [comment]
How would it differ from the current Filter search toolbar (apart from the multiple queries bit)? :)

**Comment by Daeron08** [comment]
Apparently in no way at all. I completely forgot that existed. Disregard this, my bad :)

**Comment by reupen** [comment]
Hehe, no worries :)
