### ISSUE TITLE
Lyrics takes one minute to appear

### ISSUE THREAD

**Issue by Guibuu** [reupen/columns_ui#275]
Hi,

The lyrics (the text from the tag LYRICS), at least the ones from FLAC files, takes ~1 minute to appear in the panels (like the one called 'Item details', who contains the field %lyrics%) every time any song gets played. In the first minute only appears a single dot (.).

I think this is related to issue #68

Thanks for developing Columns UI!

**Comment by reupen** [comment]
Hi,

Thanks!

#68 only related to non-playing tracks; for playing tracks foobar2000 itself should be providing full metadata.

- Where are these files stored?
- How long does take to open the standard Properties dialog for each one?
- Does the same thing happen if you add %lyrics% to e.g. the status bar?

**Comment by Guibuu** [comment]
Sorry for the delay. I can provide you a little more information:
- The strange behaviour happens with FLAC files. If I convert that song to MP3, %lyrics% loads instantly.
- It takes the same time to load the lyrics on both a mechanical hard drive than an SSD (~1 min).
- It takes <1 second to open the standard Properties dialog.
- Yes, the same behaviour happens if I add %lyrics% to the status bar. It also takes 1 minute to load there.
- Sorry, I don't know where to look for the tracking mode.
- [This is a test song](https://www.dropbox.com/s/php87boircsc0ci/Test%20for%20lyrics.flac?dl=0) (CC BY 3.0) with 'lorem ipsum' text as %lyrics%.

**Comment by reupen** [comment]
Now you mention it, this was noted in the change log: https://github.com/reupen/columns_ui/blob/master/CHANGELOG.md#item-details-panel

I'm not sure it can or should be fixed in Columns UI.

However, you can work around this by editing `LargeFieldsConfig.txt` in your profile directory (this directory can be opened by holding Shift and clicking File and then Browse configuration folder).

**Comment by Guibuu** [comment]
Thank you very much for the workaround.

Now I'm pretty sure it's not a Columns UI's bug. Sorry for the inconvenience!
