### ISSUE TITLE
Output device toolbar not displaying full list

### ISSUE THREAD

**Issue by Dreista** [reupen/columns_ui#281]
I have a lot of entries in the output devices, but it looks like the output device toolbar only displays a maximum of 30 entries based on the selection.

For example, here is a list of 50 entries.

- Entry 0;
- Entry 1;
- Entry 2;
- …
- Entry 48;
- Entry 49.

# Observed Behavior

- If entry 0 is selected, the dropdown menu of the toolbar will display entry 0 - 29;
- If entry 5 is selected, the dropdown menu of the toolbar will display entry 5 - 34;
- If entry 45 is selected, the dropdown menu of the toolbar will display entry 20 - 49;
- If entry 49 is selected, the dropdown menu of the toolbar will display entry 20 - 49.

# Expected Behavior

Columns UI displays all output devices (just as what DUI do).

I'm not really sure if it is intended behavior or just a bug.

**Comment by reupen** [comment]
Hi,

Thanks for the report. There is a scroll bar missing – I'll fix that soon.

However, when you say that the Default UI displays all entries, do you mean it displays a scroll bar, or that it displays a taller list?

Thanks

**Comment by Dreista** [comment]
Default UI displays a scrollbar.
