### ISSUE TITLE
Button Icons not appearing on fb startup but only after the options are open and OK'd

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#296]
See here the issue.

Some info before I start:
1. All my plugins and fb are up to date.
2. OS is **Version: 1909**
2. Running in portable mode.
3. Using relative paths for the `.ico` files.

![new gif](https://user-images.githubusercontent.com/14054664/76078589-de747d80-5f9a-11ea-85e6-86b676016eff.gif)

 I'm using relative paths. Direct paths are working ok. The relative paths work but only when I do what I'm showing in the gif above.

**Comment by reupen** [comment]
Thanks for the report. I can see there was a regression in 1.4.0 relating to relative paths there.

I'll restore the 1.3.0 behaviour.

**Comment by stephen147** [comment]
No worries, thanks for the quick reply.

**Comment by reupen** [comment]
The problem I found in 1.4.0 would only affect image file extensions other than .ico and .bmp. 

Are you sure they're .ico files? Does version 1.3.0 work correctly?

**Comment by stephen147** [comment]
Sorry, when I wrote .ico I meant .png files. 

Yes, that older version worked correctly if I recall.

**Comment by reupen** [comment]
That makes more sense. You can try the version built in #298 by downloading it from here: https://reupen.visualstudio.com/Columns%20UI/_build/results?buildId=806&view=artifacts&type=publishedArtifacts

If you hover over the 'VS 2019 v142 Release' item a down arrow will appear on the right-hand side. If you click that a zip file will be downloaded which will contain a test build in `VS 2019 v142 Release\vc16\Release`.

**Comment by stephen147** [comment]
Thanks very much. Just redirected the pngs to a relative path and all is good in the world again.
