### ISSUE TITLE
How do I display the album count in the status bar and pane

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#297]
See in the settings here: 

![image](https://user-images.githubusercontent.com/14054664/76113030-45198b80-5fdb-11ea-9862-e7ade4c8620b.png)

Is that achievable to return the album count here?

**Comment by reupen** [comment]
No, that's not possible.

**Comment by stephen147** [comment]
Is it possible to add a checkbox similar to the **show total length of selected tracks** only for album count?

**Comment by reupen** [comment]
It would be on the difficult side, I'm afraid. At the moment, that title formatting field only really has access to information about the playing track. And calculating an album count would involve examining the metadata of all tracks in the playlist (or communicating with the playlist view if it is one with grouping turned on).

I think it's unlikely to happen, so I'm going to close this.

**Comment by stephen147** [comment]
Okay. Thanks. I thought something like this would be a popular request. No worries.
