### ISSUE TITLE
Filter Search request: Implements time expressions: AFTER, DURING LAST, DAYS, WEEKS

### ISSUE THREAD

**Issue by Nojevah** [reupen/columns_ui#299]
In Foobar2000 default "Media Library Search", we can use all this:
https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Query_syntax#Time_expressions

Unfortunately, as example,
_%last_modified% DURING LAST 2 WEEKS_
does not work.
I suspect it's because it's not implemented in Columns UI. Hence the request for implementation, hoping it's not a failure by me.

**Comment by reupen** [comment]
Thanks for the report. I can reproduce that – it seems it's related to the API version in use. I'll have a look at it.
