### ISSUE TITLE
Cannot use _LENGTH in the properties panel

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#303]
See here where I'm adding the length to the settings only it doesn't show up in the panel.

It would be nice to be able to add other things that are in the general data checkbox but give the user the ability to customise their own.

![image](https://user-images.githubusercontent.com/14054664/79474415-44264180-7ffe-11ea-8a66-9eb2801c65e1.png)

**Comment by reupen** [comment]
That configuration will only work for metadata fields; `_LENGTH` is not such a field.

If you want to see the length of tracks, you need to enable the 'General' information section. It will then be displayed under Duration.

**Comment by stephen147** [comment]
Oh, that's a shame. Thanks for letting me know.

It would be nice if you could add an option of which items show when the general info is checked but no sweat if not.
