### ISSUE TITLE
Add auto completion of genres in the properties panel like the playlist view

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#304]
See attached to what I'm referring. 

![image](https://user-images.githubusercontent.com/14054664/79514452-195bdd80-803e-11ea-9a79-cecf013ce278.png)

**Comment by reupen** [comment]
Yes, that is a fair request 🙂

**Comment by stephen147** [comment]
Thanks. Makes a changes from my others 😂

**Comment by stephen147** [comment]
Hi @reupen, I was just wondering have you this request on the agenda?

**Comment by reupen** [comment]
Hmm, it's still a fair request 😄 I've added it to [the board](https://github.com/reupen/columns_ui/projects/1) so it's remembered.

**Comment by stephen147** [comment]
ha, thank you @reupen.

**Comment by stephen147** [comment]
Thanks for this addition @reupen
