### ISSUE TITLE
In Playlistview CODEC and __ENCODING wrong shown

### ISSUE THREAD

**Issue by ASopH** [reupen/columns_ui#305]
Hi, I have found a small error. In the File Type ATSC A/52 is displayed at% codec% in the built-in Playlist AC3 only. The %__encoding variable is shown as ?. In the Item Details however ATSC A/52. The % __ Encoding% variable is displayed.
![CUI](https://user-images.githubusercontent.com/14108704/79631806-7dc08f00-815b-11ea-9920-4409f4990db9.png)
Thanks for the CUI, and remains healthy

**Comment by reupen** [comment]
Hello,

Does it change in the playlist view when the track is being played?

**Comment by ASopH** [comment]
Yes, I had not tried... do you need a sample?

**Comment by reupen** [comment]
Try clicking on Tools in the properties window and then Reload info. If it persists, then yes, I can check what's going on with a sample file. But it's not likely to be related to Columns UI.

**Comment by ASopH** [comment]
When I re-loading is the correct information appears ... It is remarkable that this phenomenon happens only in the CUI. Never in the DUI ...
After Exiting foobar, and restart the correct information is displayed. Maybe it's the format of the files. The files are stored in mka format. I invite with a sample, maybe it helps.
[01 - Neuland - Cascade 39.zip](https://github.com/reupen/columns_ui/files/4496711/01.-.Neuland.-.Cascade.39.zip)
Thank you very much for your effort!

**Comment by ASopH** [comment]
It is also strange that appears correctly in the Item Details the information.

**Comment by reupen** [comment]
OK, so you were probably seeing cached information from an older version of the AC3 input or foobar2000 itself. There should be no difference between Default UI and Columns UI in this respect. Perhaps you were looking at different files?

Item details will often read file info afresh to allow for the display of lyrics, that's why it was displaying different information.
