### ISSUE TITLE
Glitch - Option buttons - When big number of buttons, dragging is very difficult

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#306]
As you can see when I have a big number of buttons, then dragging them around is very difficult.

It would be nice if this could be slowed down while dragging to allow easier placement.

![Sx0Jk0EU7Q](https://user-images.githubusercontent.com/14054664/79920767-c6f93300-8428-11ea-99c9-8e046fd42ca2.gif)

Created a separate issue for resizing the dialog here. https://github.com/reupen/columns_ui/issues/309

**Comment by reupen** [comment]
There both valid points, but also separate ones 🙂  Do you mind splitting the resizing one into a separate issue?

**Comment by stephen147** [comment]
https://github.com/reupen/columns_ui/issues/309 Here's the one for resizing. I'll leave the dragging issue here.
