### ISSUE TITLE
Time elapsed of current playing track doesn't show in other playlists.

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#308]
If I click on a track in one playlist, it will show `[%_time_elapsed% / ]%_length%` ok in that playlist.

But if I go to another playlist with the same track in that, it doesn't have this info.

![new gif](https://user-images.githubusercontent.com/14054664/80007656-76ccb000-84be-11ea-9dab-7b72246df8f3.gif)

**Comment by reupen** [comment]
This is really a behaviour of foobar2000 itself I'm afraid – in the context of a playlist, only the original playlist item is considered to be playing. So, I don't think it's something for Columns UI to find a solution for.

**Comment by stephen147** [comment]
Okay, thanks for confirming.
