### ISSUE TITLE
Question - How can I fix the green text colour of a selection

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#311]
I have this in the Columns>Display script tab.

```
$puts(1star,$rgb(128,128,128)★)
$puts(2star,$get(1star)$rgb(108,108,108)★)
$puts(3star,$get(2star)$rgb(88,88,88)★)
$puts(4star,$get(3star)$rgb(68,68,68)★)
$puts(5star,$get(4star)$rgb(48,48,48)★)
$puts(6star,$get(5star)$rgb(255,70,190)★)
$puts(7star,$get(6star)$rgb(255,0,128)★)

$ifequal($right(%comment%,1),1,$get(1star),)
$ifequal($right(%comment%,1),2,$get(2star),)
$ifequal($right(%comment%,1),3,$get(3star),)
$ifequal($right(%comment%,1),4,$get(4star),)
$ifequal($right(%comment%,1),5,$get(5star),)
$ifequal($right(%comment%,1),6,$get(6star),)
$ifequal($right(%comment%,1),7,$get(7star),)
```

## Here's the screenshot of that setting
![image](https://user-images.githubusercontent.com/14054664/80850644-ee17e780-8c14-11ea-8cd5-e3afae38e320.png)

This column is for showing stars. 1-7 based on the comment tag which is this for example `08A - 5 - R7`

But is showing as green when I have that row selected. I've disabled all other styles that I'm aware of but the problem still remains.

## The rating row
Notice the green text for the 6th and 7th star.

![image](https://user-images.githubusercontent.com/14054664/80850711-3931fa80-8c15-11ea-8143-1aca6de4f4ba.png)

**Comment by reupen** [comment]
If you only supply three arguments to $rgb(), it will set the selection text colour to the inverse of the colour you specify.

Try the six-argument form of $rgb(): https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.24rgb.28r1.2Cg1.2Cb1.2Cr2.2Cg2.2Cb2.29

**Comment by stephen147** [comment]
Ah, thanks so much!!

```
$puts(clrstart,$rgb(200,200,200,255,255,255))
$puts(clrend,$rgb(80,80,80,255,255,255))
$puts(clr6star,$rgb(255,80,198,255,255,255))
$puts(clr7star,$rgb(255,0,128,255,255,255))

$puts(5stars,$ifgreater($right(%comment%,1),5,,$transition($repeat(★,$right(%comment%,1)),$get(clrstart),$get(clrend))))
$puts(5starsplus,$ifgreater($right(%comment%,1),5,$transition($repeat(★,5),$get(clrstart),$get(clrend)),))

$get(5stars)

$ifequal($right(%comment%,1),6,$get(5starsplus)$get(clr6star)★,)
$ifequal($right(%comment%,1),7,$get(5starsplus)$get(clr7star)★★,)
```

![image](https://user-images.githubusercontent.com/14054664/80917344-2541e200-8d56-11ea-8980-3013f199d4a5.png)
