### ISSUE TITLE
Bug in artworkview for stub images?

### ISSUE THREAD

**Issue by ASopH** [reupen/columns_ui#314]
Hello :)

I entered different images for missing pictures of front, back, artist and disc. Unfortunately, only the picture for front is displayed when one or more image for the other types are missing.

I've tested the same pictures in DUI and there is all ok.

Many thanks and stay healthy!

**Comment by reupen** [comment]
Hi,

Thanks for the report. Indeed, there's a comment to that effect in the source:

https://github.com/reupen/columns_ui/blob/6276a1a5cb551a1563c981d91bc32deaf7bd1597/foo_ui_columns/artwork_helpers.cpp#L273

It shouldn't be too hard to fix – I'll have a look when I have a chance.

Thanks
