### ISSUE TITLE
Sudden Crash with item details

### ISSUE THREAD

**Issue by ASopH** [reupen/columns_ui#321]
Hello,
I have the following problem:
'Item detais' with this sequence:

$if($stricmp($left(%path%,4),http),📻,💿 )[%album%[ '('$year(%date%)')']$ifgreater(%totaltracks%,1, `'['%tracknumber%/%totaltracks%']',)]

Often when I click in the Playlist to a untagged file foobar crashes . This does often/but not always happen, and rarely it creates a crash-log.
If I remove the sequence  by a "//" I had no mistakes.

annexed rarely crash-logs. I hope they can help.
[crash reports.zip](https://github.com/reupen/columns_ui/files/5057602/crash.reports.zip)

Best regards
Arne

**Comment by reupen** [comment]
Thanks for the report and repro steps – I've reproduced the problem.

It's happening because the Windows API function Items details uses ([ScriptString_pcOutChars](https://docs.microsoft.com/en-gb/windows/win32/api/usp10/nf-usp10-scriptstring_pcoutchars)) to work out how many characters fit in the available space is counting the emojis as two code points each, while I was under impression they were one each. Other functions in that area of the API (Uniscribe) seem to be doing the same.

I'll need to investigate a bit further about how to fix this. But it's affecting those two emojis as their code points in hex are above FFFF. I'd suggest avoiding them for now.

**Comment by ASopH** [comment]
Hello!
Thanks for the information. The troubleshooting has made me a little crazy. I have the symbols once replaced by words.

Thank you and stay healthy.
Arne

**Comment by reupen** [comment]
Just a note to say I'm still working on a fix. I've needed to rewrite the word wrapping logic (which is complex due to font and colour code support).

Hopefully I'll have something to test in a few days or so.

**Comment by ASopH** [comment]
Nice to hear. I'll take a look then.

**Comment by reupen** [comment]
Hi,

I have a development version available to test:

[Development version](https://artprodcus3.artifacts.visualstudio.com/Ac14dc90d-58e8-48df-a92d-d34cda9b6d7e/b518cdbd-8215-43ba-adb7-db580f6fd944/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3JldXBlbi9wcm9qZWN0SWQvYjUxOGNkYmQtODIxNS00M2JhLWFkYjctZGI1ODBmNmZkOTQ0L2J1aWxkSWQvODYyL2FydGlmYWN0TmFtZS9WUysyMDE5K3YxNDIrUmVsZWFzZQ2/content?format=zip)

In that archive, within `VS 2019 v142 Release\vc16\Release\` you'll find an `.fb2k-component` file that you can install in the usual way (you can ignore the `.pdb` file).

The crash should be gone, but I'd check that other Item details functionality like `$set_font()`, `$rgb()` and word wrapping is still working well if you were using those before.

Thanks!

**Comment by ASopH** [comment]
Hello and thanks!
I've tested... crash semms to be gone, but the horizontal alignment in item details is broken. LEFT is ok, but CENTER looks like <left center> and right is out of frame!
$rgb() seems to be ok, $set_font I'd never used. 
$tab() with no effect (a long time ago). I believe, it's a DUI-problem. I don't have a hydrogenaudio-account to post this.

thanks for your time :-)

**Comment by reupen** [comment]
Thanks for testing!

I've put a fix in for the alignment – [here's a new version](https://artprodcus3.artifacts.visualstudio.com/Ac14dc90d-58e8-48df-a92d-d34cda9b6d7e/b518cdbd-8215-43ba-adb7-db580f6fd944/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3JldXBlbi9wcm9qZWN0SWQvYjUxOGNkYmQtODIxNS00M2JhLWFkYjctZGI1ODBmNmZkOTQ0L2J1aWxkSWQvODY2L2FydGlmYWN0TmFtZS9WUysyMDE5K3YxNDIrUmVsZWFzZQ2/content?format=zip).

`$tab()` has a bit of a history. In some contexts it's used for right-alignment and pseudo-columns. In Default UI this is just in the status bar now I believe. I assume you were after normal tab indentation support – it's not a simple matter so it's generally not supported in Columns UI.

**Comment by ASopH** [comment]
Thanks for the info about $tab()!
It seems that the error is gone - the crash and the alignment. 
I can see no other error in this case. You can close this if you want.

Thanks again :-)

**Comment by reupen** [comment]
Great, thanks for testing!
