### ISSUE TITLE
Question - How do I set an rgb value to a varialble for setting the style

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#341]
I've tried to use this in **Playlist view>Globals>Variable** tab.

```
$set_global(txtclrhighlightvalue,216,237,201)
$set_global(txtclrhighlight,$rgb($get_global(txtclrhighlightvalue)))
```

And then use this to set it:
```
$rgb($get_global(txtclrhighlightvalue))
```

I want to expose the `txtclrhighlightvalue` value to be used elsewhere which is the reason for creating its own variable for it but I cannot get this to work.

**Comment by marc2k3** [comment]
`$setglobal` takes 2 arguments, a name and a value, you can't pass it 3 values. However you can pass `$rgb(216,237,201)` as a single value. It's already been perfectly answered the first time you asked...

https://hydrogenaud.io/index.php?topic=119798.msg987437#msg987437

**Comment by reupen** [comment]
The answers given have covered the options available. 

For information, title formatting only really has strings, and not more complex types like arrays or lists. So you can't really pass around lists of values without encoding them into a string, which is what $rgb() does already.
