### ISSUE TITLE
[Request] A dedicated playlist for files opened via Explorer

### ISSUE THREAD

**Issue by bukakow** [reupen/columns_ui#343]
I would like individual music files to open in a specific playlist instead of creating New Playlist, New Playlist (2), New Playlist (3) etc.
Or at least to make such an option.
I tend to open individual files and then I have to delete several or more New Playlists-things
![obraz](https://user-images.githubusercontent.com/36563739/93077513-2e8a7600-f689-11ea-9f80-bf5a60f7d592.png)

**Comment by reupen** [comment]
Could you confirm how exactly you're creating these playlists? The string 'New Playlist' exists in the foobar2000 SDK, but not in Columns UI itself.

**Comment by bukakow** [comment]
Thanks! It worked.
To reproduce:
1. Have an **auto-playlist** active.
2. Open a file from explorer.

**Comment by reupen** [comment]
Ah, OK, that explains it.
