### ISSUE TITLE
Items properties panel - Issue when selection has multiple values, panel only shows one.

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#357]
In this example, Compilation varies on the selection but in the panel, it only shows one.

![image](https://user-images.githubusercontent.com/14054664/102014936-75ebd580-3d50-11eb-9fbc-2261f7282571.png)

**Comment by reupen** [comment]
I assume some of the tracks don't have COMPILATION set at all? Yes, that does look misleading.

**Comment by stephen147** [comment]
Yes, that's right. This goes for all other tags as far as I can see.

**Comment by stephen147** [comment]
Thanks for the fix. When will it be released?

**Comment by reupen** [comment]
Hi,

In the next couple of weeks, hopefully.

But you're welcome to try a development build. The repo README gives instructions for downloading them – [here's a direct link to what's currently the latest one](https://artprodcus3.artifacts.visualstudio.com/Ac14dc90d-58e8-48df-a92d-d34cda9b6d7e/b518cdbd-8215-43ba-adb7-db580f6fd944/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3JldXBlbi9wcm9qZWN0SWQvYjUxOGNkYmQtODIxNS00M2JhLWFkYjctZGI1ODBmNmZkOTQ0L2J1aWxkSWQvMTA0Ni9hcnRpZmFjdE5hbWUvVlMrMjAxOSt2MTQyK1JlbGVhc2U1/content?format=zip).

**Comment by stephen147** [comment]
Thanks, I'll wait until the official release.
