### ISSUE TITLE
Dynamic album covers

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#365]
Since foobar2000 1.6.6 beta 1, "support for internet radio album art" is added. Unfortunately CUI Artwork view panel can't handle Dynamic album covers. "Dynamic album covers are propagated via now_playing_album_art_notify_manager API (available since v1.4 series), not every component utilizes it". (Peter) https://hydrogenaud.io/index.php?topic=120855.msg996424
Could you make it work?

**Comment by reupen** [comment]
Hi,

Thanks for pointing it out. I'll have a look at it.

**Comment by reupen** [comment]
I'd note that the interface in question is quite limited from what I've seen so far:

- it doesn't deliver any notifications when artwork is being loaded or when the track has no artwork
- it only supports front covers
- sometimes it doesn't deliver a notification if a new track has the same artwork as the previous track (but sometimes it does, this appears to be based on metadata including the DATE field which is odd, at that has no bearing on reading artwork)

This does make integrating it into the artwork view panel non-straightforward, as those aren't entirely compatible with long standing behaviours of the artwork view panel. Hopefully, though, it can still be made to work with a bit of creativity.
