### ISSUE TITLE
Suggestion - Add a magnifying glass like Traktor to search

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#373]
See attached the magnifying glass that appears when you hover over an artist, album etc.

It would be a nice quick way to filter out genres, artists etc. by creating a new playlist with the searched item.

![image](https://user-images.githubusercontent.com/14054664/119131176-0bdb0900-ba31-11eb-89aa-3cb278cb0e2a.png)

**Comment by reupen** [comment]
Hi,

Something similar could easily by achieved via a context menu command – for example, I know the old [Database Search](https://foosion.foobar2000.org/components/?id=dbsearch&version=1.4) components has similar context menu commands.

For that reason, I don't think this needs to be built into the playlist view directly. Sorry.

**Comment by stephen147** [comment]
No worries. I thought it would be a nice feature for any item a user would like depending on what columns are shown.
