### ISSUE TITLE
When I rotate screen some columns are completely hidden, inacessible by scrolling in NG playlist

### ISSUE THREAD

**Issue by mzso** [reupen/columns_ui#38]
Hi!

I have five six columns and bunch of other stuff to the left of the playlist.
When I rotate a scrollbar appears to, but even so the last columns disappears. It was like in this in 0.3.8.8 and now 0.5.

**Comment by reupen** [comment]
Hi,

Thanks for the report.

I tried a screen rotation but things seemed OK here. So, a few questions...

* What version of Windows?
* Could you post a screenshot of the problem or a video?
* Which playlist view (NG or Columns playlist)?
* Could you post a screenshot of the layout preferences tab, and an FCL file (if possible)?

Thanks

**Comment by mzso** [comment]
Windows 8. Though I doubt it matters. (I already mentioned in the title that it's NGplaylist)
Here are screenshots:
![landscape](https://cloud.githubusercontent.com/assets/4479090/17862447/86cd2640-6895-11e6-8b5d-ba622e4101ea.PNG)
![portrait-left](https://cloud.githubusercontent.com/assets/4479090/17862446/86cb9f14-6895-11e6-8ccf-cb787483fee4.PNG)
![portrait-right](https://cloud.githubusercontent.com/assets/4479090/17862448/86cdf796-6895-11e6-844a-bc5c0b396bfa.PNG)

I don't know what's an FCL file is, or how to get it. Also the layout definitely doesn't fit into the textbox.

**Comment by mzso** [comment]
So is this what you meant by FCL?

[CUI-layout.zip](https://github.com/reupen/columns_ui/files/430648/CUI-layout.zip)

Unfortunately it seems like there's no way to only export one layout (I use the default), so there are other junk layouts in there.
(I'm hoping there aren't any personal data in this. I didn't see any when I skimmed it. )

**Comment by reupen** [comment]
Thanks. The bug is fixed for the next version. It was not directly related to screen rotation; mainly it was that the scroll bar did not take the width of the artwork column into account in calculating the maximum position.

**Comment by mzso** [comment]
Cool.
Approximately when is it due?

**Comment by mzso** [comment]
I just noticed something else. When the screen's rotated the lines after the group titles are not continuous.
And as I scroll left/right bigger/smaller gaps appear. It also never seems to reach the far right.

**Comment by reupen** [comment]
Thanks, I noticed that too. It's also fixed for the next version.

No ETA at present. If more bugs crop up then I'll do a patch release. Otherwise, it will have to wait for the next minor release. It's fairly straightforward to compile the source code, though :)
