### ISSUE TITLE
Displayed track (automatic options)

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#383]
Not sure if it's intended behavior or the functionality has been switched by error, but any of the 2 automatic options always give priority to playing track.  Although they are listed in opposite order.
i.e. if there is a track playing, no matter if you select another track, the cover comes from now playing track. 

In DUI, if you set "viewers" to selected track it's the opposite. Selection gets priority and playing track is used as fallback (even if you select another track at the playing playlist, if you switch to an empty playlist, is the now playing artwork the one displayed). 

![DUI](https://user-images.githubusercontent.com/83307074/123864938-d6bcb300-d91a-11eb-936b-64989e337490.gif)

Maybe is a  design choice, although it would be great to also have the opposite behavior.

Then... using "Cursor follows playback" makes artwork go back to now playing track in DUI, but that doesn't happen on CUI (it prefers the current selection from current playlist, even when last selection was done at other playlist). On both Current selection and Current playlist modes. This one seems a bug, since current selection mode would be in fact associated to the last selection, don't you think?

![CUI](https://user-images.githubusercontent.com/83307074/123865214-27341080-d91b-11eb-9274-90f941bcba14.gif)

**Comment by reupen** [comment]
On the first point, if I recall correctly, I looked into it for Item properties for #57. The problem, as I recall, was that these panels don't exclusively use what foobar2000 reports as the current selection, and also have their own logic in relation to the playing track. Therefore, the setting in Preferences doesn't have any effect. The value of that setting isn't exposed in the SDK either, so it can't be incorporated into the logic used by the various panels.

It could still be solved by adding a setting for each panel – which I'm open to.

On the second point, I tried but wasn't able to reproduce any special logic in Default UI relating to artwork and Cursor follows playback. The steps I followed were:

1. Select 'Prefer current selection' in Preferences
2. Switch to a Default UI layout containing Playlist tabs and the default playlist view
3. Switch to playlist B and select a track
4. Switch to playlist A and play a track
5. Advance to the next track
6. Click on the tab for playlist B

The artwork for the track that was/is selected in playlist B is displayed.

If I've misunderstood, could you provide some amended steps?

Thanks

**Comment by regorxxx** [comment]
> It could still be solved by adding a setting for each panel – which I'm open to.
It would be great, since that would allow fully customization of which one takes priority.

> On the second point, I tried but wasn't able to reproduce any special logic in Default UI relating to artwork and Cursor follows playback. The steps I followed were:
Sorry, after seeing the gif myself it was clearly not so obvious.
1. On artwork panel: Displayed track/Current selection
2. Preferences/Playback/Cursor follows playback (checked). Note this one changes selection even if you are in another playlist, although playlist view is not switched to it ("background selection").
3. Create Playlist A with 2 tracks with different artwork.
3. Create Playlist B with 1 track with different artwork (to the 2 previous tracks).
4. Play first track (A1) on Playlist A.  Artwork should be A1.
5. Switch to Playlist B, **don't** select track (B1). Artwork will be B1 on CUI. In DUI it's still A1 since you have selected nothing!
6. Play next song using next button while being on Playlist B. Now A2 should be playing, but artwork will be from B1 on CUI. On DUI artwork changes to A2 until you re-select anything else.
7. If you go back to Playlist B A2 should be selected as expected and artwork will change to it on CUI. On DUI that was the artwork being displayed. 

Not sure about the terminology used on SDK  but A2 is a focused and selected track (following Spider Monkey panel terms), while B1 is only the focused track. In DUI the selected item gets precedence over only focused items, even if it's from another playlist. In CUI it's like the selected item and focused ones are equivalent.

In fact after testing it again that's the "problem". CUI always consider the first item on playlist as "selection" even if you did not really selected it, while DUI has a "no selected" state if you selected nothing on current playlist (falling back to playing item on playing playlist). The gifs should show it clearly now.
![DUI sel](https://user-images.githubusercontent.com/83307074/129086215-761ce664-769f-42dc-b4f2-54900a0363e1.gif)
![CUI sel2](https://user-images.githubusercontent.com/83307074/129086240-4a78d587-e6e2-4217-be6c-736f74aeedad.gif)

**Comment by reupen** [comment]
> In DUI the selected item gets precedence over only focused items, even if it's from another playlist. In CUI it's like the selected item and focused ones are equivalent.

I don't believe that's true – it's simply showing the playing track as a fallback as there is no selection (and it's not related to Cursor follows playback).

> In fact after testing it again that's the "problem". CUI always consider the first item on playlist as "selection" even if you did not really selected it, while DUI has a "no selected" state if you selected nothing on current playlist (falling back to playing item on playing playlist). The gifs should show it clearly now.

Current selection applies to whatever (child or top-level) window is focused, and not just the playlist.

In CUI you're using the playlist switcher component and the focus changes to it when you click on it.

In DUI you're using the playlist tabs – the focus doesn't change for tabs with a single click. If you click again slowly the focus will change and the artwork displayed will change.

If you used e.g. [foosion's Playlist Manager](https://foosion.foobar2000.org/components/) in DUI you would get the same behaviour as CUI.

If you used the Playlist tabs in CUI you would get similar behaviour to DUI (though note the CUI Playlist tabs don't report a selection even when focused).

The last thing to note is that the behaviour of the CUI and DUI artwork views is different when multiple items are selected. CUI just displays the artwork from the first track, while DUI does something else.

**Comment by reupen** [comment]
Closing as the first point is covered by #57 and there are no noted actions for the second point.
