### ISSUE TITLE
Drop mark is black over black background

### ISSUE THREAD

**Issue by mzso** [reupen/columns_ui#39]
I have a layout with a black/dark background and white text. When I drag a playlist or a song the mark is also black making it nearly invisible.

![landscape](https://cloud.githubusercontent.com/assets/4479090/17862447/86cd2640-6895-11e6-8b5d-ba622e4101ea.PNG)

I didn't even know there was a drop mark until I recently noticed it by accident.

It looks like it's designed for a light background only. It's color should depend on the colors selected for the ui.

**Comment by mzso** [comment]
Hi!

Now there's a number of fixes I'm eager to test/try. Could you make a new beta release?

**Comment by reupen** [comment]
Yes, I will release 0.5.1 beta in the next few days.
