### ISSUE TITLE
Toolbar when text is added to a button issues

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#398]
See here the two problems below in the screenshot.

![image](https://user-images.githubusercontent.com/14054664/138121664-07b8db78-9bef-4fbe-a39a-8b68d4a4b7ef.png)

**Comment by reupen** [comment]
Hi,

If you change 'Text location' to 'Right', it should display vertically centred instead.

(That option applies to the entire toolbar – it's not possible to set it individually for each button as the Windows toolbar control doesn't support that. But you can add multiple button toolbars if needed.)
