### ISSUE TITLE
"Sort incoming files by" has no effect, wacky sorting.

### ISSUE THREAD

**Issue by mzso** [reupen/columns_ui#40]
Hi!

I always noticed that sorting was wacky and didn't make any sense when I added files without tags.
For example I get this when I drop incrementally named files or their folder:
```
6
8
4
7
1
3
2
5
```

But now  after testing a bit I realize the "Sort incoming files by" feature has no effect at all. No matter what I change it to... I don't know what kind of sort ordering is active, but it's not what's set here.

**Comment by reupen** [comment]
The 'Sort incoming files by' on the 'Shell Integration' page works for me when dragging and dropping files on NG playlist or the main window (window title/toolbars/etc.) once the setting change has been applied.

Where are you dropping the files? Are the files being dragged from Windows Explorer?

**Comment by mzso** [comment]
[**@reupen**](https://github.com/reupen) commented on [2016. aug. 25. 21:58 CEST](https://github.com/reupen/columns_ui/issues/40#issuecomment-242516467 "2016-08-25T19:58:41Z - Replied by Github Reply Comments"):
> The 'Sort incoming files by' on the 'Shell Integration' page works for me when dragging and dropping files on NG playlist or the main window (window title/toolbars/etc.) once the setting change has been applied.
> 
> Where are you dropping the files? Are the files being dragged from Windows Explorer?

Okay. So I wasn't looking there... :)
I was looking at Columns UI > Filters > Behavior > "Sort incoming files by"
Then what does that control? Or all the filters section for that matter.

**Comment by mzso** [comment]
Anyway thanks for the help.

**Comment by reupen** [comment]
They're for the panel named Filter. The 'Sort incoming files by' there controls the order of the files when they're added to a playlist.

No problem :+1:
