### ISSUE TITLE
[Request] Add a "Close hides" option.

### ISSUE THREAD

**Issue by krizalidzero** [reupen/columns_ui#412]
I am new to this UI and... well, it is basically perfect, especially compared to the default one.
But, unlike the default one, there does not seem to be an option to click on X and have the app hide/minimize, it only closes.

Is this behavior something we can have?

Regardless, thank you!

**Comment by reupen** [comment]
Hello,

Have you tried the 'Close to notification area icon' on the Advanced preferences page?

![image](https://user-images.githubusercontent.com/12693549/147079110-f38e06f7-fc39-4ec2-9587-4c76c5cf3d49.png)

**Comment by krizalidzero** [comment]
Hi.
Thank you for the feedback.

In all honesty, I had not noticed that setting until your email came.
I tried it a few times and it does not seem to work. Any ideas?

Thank you.
Miguel.

**Comment by reupen** [comment]
Hi,

Could you elaborate on what you mean when you say it doesn't seem to work? Are you having troubling toggling it, or are you not seeing a change in behaviour with it on?

Thanks

**Comment by krizalidzero** [comment]
Sorry for the unclear post.
It is checked and saved. However, closing just closes and the program does not just hide as expected.

Thanks.

**Comment by reupen** [comment]
It works here – foobar2000 stays running and an icon is shown in the Windows notification area.

Could you provide the following info to help try and work out what's going on:

- version of Windows you are using
- copy of output of 'Copy report' button in Preferences/Components
- screenshot of foobar2000

**Comment by reupen** [comment]
Currently there's nothing that can be acted on in this issue, so it's being closed. If you have any further information, feel free to reply again.
