### ISSUE TITLE
Show list of values when editing mixed values in Item properties

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#414]
Would the edit box be able to match the behaviour of how the native properties panel behaves if there are multiple values.

foobar does this when this is the case:
`«multiple values» 132858855656816505; 132858855756782989`

Whereas in the properties panel it does this in Columns UI:
`<mixed values>`

![image](https://user-images.githubusercontent.com/14054664/148280220-67b10e34-849c-4cfb-82ff-0f53308093bb.png)

**Comment by regorxxx** [comment]
Yes please. Since the properties panel lets you apply tags on batch to multiple files, the current behavior is not consistent with the rest of the UI.
