### ISSUE TITLE
[FeatureRequest]Add option show all albums of selected artist respective of genre selected.

### ISSUE THREAD

**Issue by Rexadev** [reupen/columns_ui#428]
Assuming using Genre/AlbumArtist/Album/Tracks
After selecting Artist only those albums show which are of column 1 genre, and by the time i get to tracks it is very filtered.
Is there a way to show all in that category
![Column UI show all irrespective of previous hriechy selcted](https://user-images.githubusercontent.com/62152714/150284474-88adb5ff-e475-4a6c-a9ba-70238f15af2d.png)
?
Related
https://github.com/reupen/columns_ui/issues/428
https://github.com/reupen/columns_ui/issues/427
https://github.com/reupen/columns_ui/issues/426

**Comment by reupen** [comment]
#58 is related but that would not help in your case as you have a genre selected.

I'm not entirely sure how you're using the genre field there; my suggestion would be to use multiple values for the genre field, or add an 'artist genre' field to your tracks and use that instead.
