### ISSUE TITLE
[refinement] Add a common X button to the filter search field

### ISSUE THREAD

**Issue by mzso** [reupen/columns_ui#44]
Hi!

Quicksearch fields often have a little x in the right right side to erase the input field and give it focus in one go.
I think it's a bit better than auto selecting the whole field when it gets focus. This way you can choose to edit, or delete the text in one click.

**Comment by reupen** [comment]
There is a clear button to the right of the input field. It does not focus the input, but if you wanted to overtype the search query you would just click in the text box and type as it auto-selects the content as you pointed out.

The auto-select behaviour is fairly standard for such input controls on Windows (have a look at all the major web browsers, for example). Hence, changing it would be somewhat counter-intuitive. I'm going to close this one I'm afraid, but thanks for the suggestion nonetheless.
