### ISSUE TITLE
Odd panel min/max height issue.

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#443]
My JScript Panel panel component allows setting min/max width/height and it works fine for the most part.

In this simple layout....

![image](https://user-images.githubusercontent.com/62050527/153744750-35ddd8a6-1713-41eb-9e63-81e9b1466aaf.png)

 I can add this line of code `window.MinHeight = 200;` and it works as expected. I can grab the splitter and move it up/down and it won't go below the minimum height.

But if put the put panel inside playlist tabs which in turn goes inside a horizontal splitter like this...

![image](https://user-images.githubusercontent.com/62050527/153744794-d14bb838-60de-4829-ba22-9ad20c1cafbd.png)

Setting a minimum height here locks **max height** as well and it cannot be resized.

It only seems to affect this specific combination of parent splitters???

edit: possibly relevant bits of my code.... I checked the values here are as expected...

https://github.com/marc2k3/foo_jscript_panel/blob/b1c7ef489e4e50e37e4d00f0f717e816b9bdccc3/src/Panel/PanelWindow.cpp#L69L75

and my defaults get set every time the script is initialised before the script is parsed...

https://github.com/marc2k3/foo_jscript_panel/blob/b1c7ef489e4e50e37e4d00f0f717e816b9bdccc3/src/Panel/PanelWindow.cpp#L463L467

**Comment by reupen** [comment]
Thanks, I'll have a look.

**Comment by reupen** [comment]
This should be resolved on master now, if you want to test again.

(I think there's an extra 1px being added on Windows 10 to the minimum height, but I need to investigate that a bit more as it seems to vary by OS version.)

Thanks

**Comment by marc2k3** [comment]
I'm on Windows 10 and it's fine.

```js
window.MinHeight = 200;

function on_size() {
	console.log(window.Height);
}
```

The reported value goes down to exactly 200 and not below. 

The width/height come from using WM_SIZE / GetClientRect as you would expect.

Thanks.
