### ISSUE TITLE
Playlist switcher has no cursor.

### ISSUE THREAD

**Issue by mzso** [reupen/columns_ui#45]
Hi!

This is an ancient thing, but I don't remember ever having a text cursor when editing a playlist name.

Maybe it's a similar issue to #39, maybe it's not, I can't tell. I've been using custom colors for ages.

Actually just switching back "global" to "system" or themed, doesn't bring back the cursor, so I guess there are further configuration requirements to this. (The cursor does show up with default settings, in a portable foobar instance)

**Comment by reupen** [comment]
It looks like that happens if you use a negative vertical item padding. I'll see if there's anything I can do about it, but I'd suggest just increasing the vertical item padding (Preferences/Columns UI/Playlist switcher/General) slightly.

**Comment by mzso** [comment]
[**@reupen**](https://github.com/reupen) commented on [2016. szept. 24. 15:28 CEST](https://github.com/reupen/columns_ui/issues/45#issuecomment-249364888 "2016-09-24T13:28:44Z - Replied by Github Reply Comments"):
> It looks like that happens if you use a negative vertical item padding. I'll see if there's anything I can do about it, but I'd suggest just increasing the vertical item padding (Preferences/Columns UI/Playlist switcher/General) slightly.

Indeed. Though there's a reason for that. It brings rather significant space savings.

**Comment by reupen** [comment]
Aren't we talking about an increase from -1 to 0? 😛 

There will be a fix in the next release. The edit control used for inline editing will simply always be at least as tall as the font.
