### ISSUE TITLE
Make pressing enter not close the grouping settings panel

### ISSUE THREAD

**Issue by Daeron08** [reupen/columns_ui#48]
Right now if you go to the grouping settings page and edit one of the scripts, pressing enter in the textarea will immediately close the dialog window. This makes it hard to work with multiline scripts or just simply adding new lines for visibility. It also feels inconsistent with the rest of the UI as you can generally insert enter without a problem elsewhere. A bigger textarea or a resizable window would be nice too, but not a big deal.

**Comment by reupen** [comment]
Thanks, most probably an oversight, but it should be a simple fix.
