### ISSUE TITLE
master-download not complete

### ISSUE THREAD

**Issue by ASopH** [reupen/columns_ui#50]
The directorys mmh, pfc, ui_helpers are empty - how can I download these dirs?

**Comment by zao** [comment]
They are git "submodules". Part of the tree is stored in other git repositories and this repository just stores references to commits in those repositories.

After cloning the respository, you need to `git submodule init` and `git submodule update --recursive`
Or you can do it at clone-time by `git clone --recursive https://github.com/reupen/columns_ui.git`

**Comment by ASopH** [comment]
thx for information :-), btw. great work !!
