### ISSUE TITLE
Access to allow_locked_panel_resizing setting

### ISSUE THREAD

**Issue by dima-lur** [reupen/columns_ui#53]
Hi, I don't see any access to settings::allow_locked_panel_resizing from custom splitter. However it is only for "Horizontal and vertical splitters", isn't it?)

**Comment by reupen** [comment]
It wasn't exposed publicly, but I agree it would be an improvement if it was. I'll look into using config_object  to do that (for which, unfortunately, the documentation is a bit sparse).
