### ISSUE TITLE
ESPlaylist and Dark Mode

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#545]
I don't know, if its a problem with ESPlaylist or ColumnsUI. Dark mode doesn't work (Themed scheme).
![2022-04-22 22_30_22-](https://user-images.githubusercontent.com/15456836/164789964-ddf7a0e0-f2de-4b09-9896-40982d68b676.png)

**Comment by marc2k3** [comment]
It's to be expected and the detailed changelog mentions it...

> Third-party panels that contain system UI elements like scroll bars will need updating to fully support dark mode.

It was abandoned years ago so it obviously isn't happening.

**Comment by reupen** [comment]
Yes, I'm afraid Columns UI doesn't have any control over that and the panel would need changes made to it to support dark mode properly. For the text colour, in themed mode it's probably coming from the visual theme (which is expected) but EsPlaylist has no knowledge of dark mode so it's using the standard light mode list view.

(In general, nothing about the Windows dark mode is automatic for Win32 programs and nearly everything about it is undocumented...)
