### ISSUE TITLE
Make buttons toolbar custom hot images more robust

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#546]
The Default Button Hot Image isn't working anymore.
![2022-04-23 14_07_24-Greenshot](https://user-images.githubusercontent.com/15456836/164893965-bd0bd8ab-b798-4eb7-9458-27ed09f06065.png)

**Comment by grimes2** [comment]
Here the fcb file:
[Button7.zip](https://github.com/reupen/columns_ui/files/8546924/Button7.zip)

**Comment by reupen** [comment]
Hi,

The default icons have never had hot versions, perhaps you had custom ones before?

I am seeing a couple of problems with custom hot images though:

- .ico files don't work
- PNG files misbehave if they aren't the correct size

However, those were both problems in 1.7.0 as far as I can see. If you're seeing a difference from 1.7.0 could you compare with a portable installation?

Thanks

**Comment by grimes2** [comment]
Added pngs of light oxygen set with size 20x20 pixel as hot image. Looks good on hover.

**Comment by reupen** [comment]
That's good – are you seeing a regression from 1.7.0, then? (I need to improve the general logic around custom images in any case.)

**Comment by grimes2** [comment]
As far as I can see, there is no regression. In Version 1.7.0, I have used custom images for both normal and hot: 22x22 px pngs. The normal svg buttons in 2.0.0 alpha 1 are awesome, so I use them. The 22x22 px png for hot are too big and are cut, so I resized to 20x20 px. Please enable svg support for custom images. It seems, that Windows Imaging Component (WIC) doesn't support ico. You can drop it from the format list.

**Comment by reupen** [comment]
> As far as I can see, there is no regression.

OK – I'll repurpose this issue for fixing ICO files and making things a bit more graceful when hot images are the wrong size.

> The normal svg buttons in 2.0.0 alpha 1 are awesome

Thanks!

> Please enable svg support for custom images.

There's no native SVG support at the moment, I'm afraid (the SVGs for the default icons are converted to ICO files first). SVG support could be added using a library, though it would make more sense following #421.

> It seems, that Windows Imaging Component (WIC) doesn't support ico. You can drop it from the format list.

ICO and BMP files aren't (meant to be) loaded through WIC there – ICO seems fine for non-hot images so not sure what's going wrong for hot ones, but I'll fix it.
