### ISSUE TITLE
Support Ctrl+Backspace for deleting the last word

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#572]
<kbd>Ctrl</kbd>+<kbd>BackSpace</kbd> should delete the previous word like most programs. 

https://superuser.com/a/33153/947770

**Comment by reupen** [comment]
Ctrl+Backspace is not natively supported by the Win32 edit control. That's the reason it doesn't work, I'm afraid. For the same reason, supporting it is more of an enhancement.

(You can, of course, press Ctrl+Shift+Left and then Backspace.)

**Comment by stephen147** [comment]
No worries, thanks. Hopefully, it can be done easy enough.

**Comment by regorxxx** [comment]
Agree with this suggestion, and note it's everywhere supported on foobar.
Album list, autoplaylists, search, popup windows, context menu/properties, ....

So it's a bit confusing to have it working and most places and not in others.

**Comment by reupen** [comment]
> it's everywhere supported on foobar

Not literally everywhere – it doesn't work in many places in preferences (e.g. the album art patterns, media library file types, advanced preferences).

**Comment by regorxxx** [comment]
I was not talking about the preferences window but the actual software daily usage (and in such case this is the exception which is confusing).

Will report the preferences behavior too though, but I don't think it has the same priority since people is not working with that every day (and thus shortcuts are not needed).

**Comment by regorxxx** [comment]
https://hydrogenaud.io/index.php/topic,122847.msg1022749.html#msg1022749

**Comment by regorxxx** [comment]
It has now been fixed/implement on all input boxes on DUI from beta 26 onwards, so the previous comment doesn't apply anymore.
