### ISSUE TITLE
CUI + PSS

### ISSUE THREAD

**Issue by kan736** [reupen/columns_ui#576]
Please add the functionality of the Panel Stack Splitter plugin to the CUI. Since the original developer of this plugin stopped maintaining it, this is the only way to keep such valuable interface customization options.

**Comment by dream7180** [comment]
Strongly agree. PSS is old and outdated, but most of CUI designers have to rely on it. Now this path is blocked to x64.

**Comment by reupen** [comment]
I'm afraid I have enough to maintain already 🙂 

In any case, Columns UI has a lot built into it already. Something like that should be a separate component.
