### ISSUE TITLE
Need rebuild for foobar 2000 2.0 x64 edition

### ISSUE THREAD

**Issue by lychichem** [reupen/columns_ui#577]
Release notes here: https://www.foobar2000.org/changelog
The x64 build requires all components updated to x64 architecture. Now [Eslyric/release](https://github.com/ESLyric/release) updated to x64 build.

**Comment by reupen** [comment]
The next release will have an x64 build available.

You can use a development build if you don't want to wait. The most recent one is in the zip file here (log into GitHub first): https://github.com/reupen/columns_ui/suites/8076719750/artifacts/348262831
