### ISSUE TITLE
[dev build] fb2k v1.6.12 crashes when attempting to switch to Dark Mode

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#589]
Brand new install, no other components.

Doubt you need the crash report but I've attached it anyway...

[crash reports.zip](https://github.com/reupen/columns_ui/files/9543668/crash.reports.zip)

No problem using the same download with fb2k v2 Beta.6 x86.

**Comment by reupen** [comment]
Thanks! Should be solved by the linked PR.

(The crash log and dump was useful btw, as I failed to reproduce it on my first attempt, and I was able to link the version number back to the relevant GitHub Actions build for the symbols.)

**Comment by marc2k3** [comment]
Thanks.
