### ISSUE TITLE
Columns UI Status Pane is all black when using high contrast Windows theme

### ISSUE THREAD

**Issue by MAxonn** [reupen/columns_ui#59]
As the title says... my Foobar Status Pane is now unusable. Everything is black in it. Just a black rectangle. It happened when I switched my Windows to high contrast theme. I plan to experiment with high contrast for a period.

I have fixed it locally :). Luckily I'm preparing to soon contribute to Foobar plugin development so I started to get myself familiar with Columns UI. So, I had it running on my system and have made a modification to the code. Now it works fine. Now the question is how to submit it to the official repo. Seems like I can't create branches or pull requests.

Reupen, in case you decide to do it yourself, it's very simple. Just go to 

status_pane_msgproc.cpp

and use

GetSysColor(COLOR_WINDOWTEXT)

instead of 0 as argument to all text_out_colours_tab calls

P.S.: I should mention this is the first time I'm contributing to a public GIT repo so I might have missed some obvious way.

**Comment by reupen** [comment]
Thanks for the report. You're right, there's some funny stuff going on with the colours there.

To be able to create a PR, you first have have to fork the repo and push your branch to your fork.

However, I don't think COLOR_WINDOWTEXT is the right choice, as the background isn't using COLOR_WINDOW. From a quick look, it probably should be COLOR_BTNTEXT, as the main background colour seems to be COLOR_BTNFACE.

**Comment by MAxonn** [comment]
I'd be happy to execute this simple cosmetic fix. I take it you're happy to let me contribute this.

**Comment by reupen** [comment]
Feel free to go ahead. If I have any comments, they'll go in the PR 🙂
