### ISSUE TITLE
Customizing fonts sets them to 0pt.

### ISSUE THREAD

**Issue by Limoster** [reupen/columns_ui#620]
I was trying to change the list font size to 10pt because it was too small, and I realized that the font size was being set to "0pt". For now, I am stuck at using the "System" mode which correctly puts the font value to the default (for me it's "Segoe UI 9pt").

![image](https://user-images.githubusercontent.com/22665229/198033911-97fc6f18-08a3-44a3-b4dd-6c6d33b7ad1b.png)

**Comment by reupen** [comment]
This is caused by foo_ui_hacks. You'll need to remove it to change the font size.
