### ISSUE TITLE
(BUG) Can't change "Core" colour

### ISSUE THREAD

**Issue by LordSzechenyi** [reupen/columns_ui#654]
![3](https://user-images.githubusercontent.com/122946450/213053391-44864566-e2dd-41a9-ab43-a65483f1433d.jpg)
![4](https://user-images.githubusercontent.com/122946450/213053394-6f185d00-e4dd-441f-85a4-79b8be4dc761.png)

I don't know why....

**Comment by reupen** [comment]
Core refers to the foobar2000 core and those colours affect certain things built-in to foobar2000 (like playlist search or the pop-up version of Album List). See https://github.com/reupen/columns_ui/blob/master/CHANGELOG.md#200-alpha2 for more details. Perhaps it should be renamed 'foobar2000 core' to be consistent with the components list in preferences.

There's no configuration of the seekbar or volume bar colours available. The thumb uses the Windows accent colour in dark mode.

**Comment by LordSzechenyi** [comment]
Oh, well that sucks.

Still, playlist search also doesn't change, as I get this:
![image](https://user-images.githubusercontent.com/122946450/213474118-adb6976e-8b20-4a64-8f36-aa1e3d0fd6e8.png)

**Comment by reupen** [comment]
> Still, playlist search also doesn't change, as I get this:

It requires foobar2000 2.0, as the link I posted said.

> Oh, well that sucks.

Thanks for the insight.

**Comment by LordSzechenyi** [comment]
> > Still, playlist search also doesn't change, as I get this:
> 
> It requires foobar2000 2.0, as the link I posted said.

I do have 2.0 now, and now it's just stuck on default (white background black text)
at least its readable now, but still not what I wanted (white text on black background)

**Comment by reupen** [comment]
It should just work:

![image](https://github.com/reupen/columns_ui/assets/12693549/8463b7b5-9567-4293-a754-5e8f94db2cd6)

I'd suggest creating a new portable installation and experimenting there. If you still have problems, create a discussion, outlining what exactly you did in the portable installation and what the result was.
