### ISSUE TITLE
Caption Header bug on splitters

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#658]
I have no idea if this is a SMP bug or CUI bug, since the only component I use with a setting for the transparency option is SMP (@TheQwertiest). But I think it's a CUI thing, which doesn't really hide the header but put it on the background... similar behavior will happen with other plugins which use transparency (@marc2k3 maybe JSP?)

1. Open layout edit.
2. New blank panel.
3. Add horizontal splitter.
4. Assign to Spider Moneky Panel. (I deleted the line on the blank script which paints the background)
![imagen](https://user-images.githubusercontent.com/83307074/216570317-fe58a7f0-adf1-41cd-ab39-26b4be54b564.png)
6. Right click, configure, enable transparency.  That works fine, as it should be, using the background from CUI. 
![imagen](https://user-images.githubusercontent.com/83307074/216571100-8eb4b49f-055d-4723-a993-fe13b2ecee99.png)
![imagen](https://user-images.githubusercontent.com/83307074/216570419-e5fdc117-353e-4250-92ab-693ad8a0322e.png)
8. Now let's hide the header. Panel is shifted somewhat to the top as it should be, but header is still there
![imagen](https://user-images.githubusercontent.com/83307074/216570670-8476971b-0026-41b9-9be4-44be22abff53.png)
Is just that the panel now paints over it! (if I change the coords on the script for ex...)
![imagen](https://user-images.githubusercontent.com/83307074/216570895-0a1ac2a2-e302-44e5-a423-c63cf2f6982b.png)

![imagen](https://user-images.githubusercontent.com/83307074/216571020-2d91a6ea-81cb-4cb6-8ae5-676c436d07a4.png)

![imagen](https://user-images.githubusercontent.com/83307074/216571618-60e5f855-5bf8-4897-ab44-af53aa39e33e.png)

9. If I disable transparencies, it works as it should be:

![imagen](https://user-images.githubusercontent.com/83307074/216571193-0ebef926-5508-4731-9240-98d40c289873.png)

So well, header is not really hidden, it just get painted at other position which is usually covered by the background...

**Comment by marc2k3** [comment]
Maybe this fixes it??

```diff
diff --git a/foo_ui_columns/splitter_panel_container.cpp b/foo_ui_columns/splitter_panel_container.cpp
index 166bd16..753a7f5 100644
--- a/foo_ui_columns/splitter_panel_container.cpp
+++ b/foo_ui_columns/splitter_panel_container.cpp
@@ -124,7 +124,7 @@ LRESULT FlatSplitterPanel::Panel::PanelContainer::on_message(HWND wnd, UINT msg,
             return 0;
 
         size_t index = 0;
-        if (!m_this->m_panels.find_by_wnd(wnd, index) && m_this->m_panels[index]->m_show_caption)
+        if (!m_this->m_panels.find_by_wnd(wnd, index) || !m_this->m_panels[index]->m_show_caption)
             return 0;
 
         const auto orientation = m_this->m_panels[index]->m_caption_orientation;
```

**Comment by reupen** [comment]
Thanks for the report and thanks for investigating @marc2k3 . Yes, that regressed in ba25a338c9366b3d83eb890014a964b50facfadb it seems. Feel free to open a PR with that fix @marc2k3.
