### ISSUE TITLE
Select/Set focus

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#664]
In addition to #663 ,  or as an alternative, a 'Set focus entry'. i.e. a way to force focus to be set on current selection, for playback purposes.
'Edit/Selection/Set focus'

**Comment by reupen** [comment]
I'm not sure I follow. The focused playlist item always the last selected item in the playlist, unless you manually move focus using Ctrl-Up or Ctrl-Down.

If you mean set which track will be played when you click Play, the closest thing is probably Add to playback queue (which already exists as a context menu command).

**Comment by regorxxx** [comment]
> If you mean set which track will be played when you click Play, the closest thing is probably Add to playback queue (which already exists as a context menu command).
That's the point. 

Selecting a track and clicking play does not necessarily plays the current track (specially if you change the playlist). This was explained at #663.

Playback queue is different to that, since it simply would play that track but will never set the focus to the track selected on current playlist (and play the next ones).

Foobar differentiates between the selection shown on the UI and the internal selection used for playing. There is no way to force the second.

I'm asking about a menu entry to force that internal selection to be the current UI selected track (which in turn would force playback on current playlist from the selected track to the end). The change would apply after foobar ends the playing track.

You discarded #663 for the same reasons though.

**Comment by marc2k3** [comment]
I thought you'd use SMP for this.

https://theqwertiest.github.io/foo_spider_monkey_panel/assets/generated_files/docs/html/plman.html#.SetPlaylistFocusItem

**Comment by reupen** [comment]
> Playback queue is different to that, since it simply would play that track but will never set the focus to the track selected on current playlist (and play the next ones).

That's not my experience. When using the Default playback order, if I add a track to the playback queue on a different playlist, foobar2000 sticks to that different playlist when that track is finished.

Regardless, the UI does not control what track foobar2000 decides to play next. There is a function in the SDK to set which playlist is the playing playlist, but I suspect that won't even get the behaviour you want (and again, out of scope for the UI).

**Comment by regorxxx** [comment]
> I thought you'd use SMP for this.
> 
> https://theqwertiest.github.io/foo_spider_monkey_panel/assets/generated_files/docs/html/plman.html#.SetPlaylistFocusItem

What has to do SMP with basic foobar functionality? Obviously you can use third party plugins to set playback, the point is it should be added in the existing UI.

> When using the Default playback order, if I add a track to the playback queue on a different playlist, foobar2000 sticks to that different playlist when that track is finished.
The first part changes totally the phrase. There is no way to change playback unless you have tons of other indirect settings (like playback follows cursor, default playback order + playback queue, etc.).

There is no way to simply tell foobar, "play this track", no matter which other settings the user have. Neither for a selected track, nor for current playlist.

>  But I suspect that won't even get the behaviour you want (and again, out of scope for the UI).
That's ok. Will continue asking on native foobar then.
