### ISSUE TITLE
Make playlist view group indentation configurable

### ISSUE THREAD

**Issue by reupen** [reupen/columns_ui#671]
Requested here: https://hydrogenaud.io/index.php?msg=1021307

**Comment by reupen** [comment]
The indentation has been removed instead as it's hard to see what functional purpose it serves. This can be revisited depending on feedback.

**Comment by infectormp** [comment]
Shit happens.
I've been using foobar and Column UI for years, and the main reason I do it is to be able to use the grouping feature from Column UI. IMHO old behavior is more comfortable for the eyes. 
![image](https://github.com/reupen/columns_ui/assets/9958813/22473cb7-5d41-4d7a-a68c-93761e5bee3a)
![image](https://github.com/reupen/columns_ui/assets/9958813/a48fa324-041c-4d19-86c7-7b84bfbd65ed)
So, i rolled back to version 2.0 and will stay on it as long as possible.

**Comment by infectormp** [comment]
I vote for making indentation configurable instead of removing it.

**Comment by reupen** [comment]
Thanks for the feedback. Okay, an option will be added.

**Comment by infectormp** [comment]
Thank you!
