### ISSUE TITLE
Ctrl + Delete for deleting next word

### ISSUE THREAD

**Issue by regorxxx** [reupen/columns_ui#694]
https://hydrogenaud.io/index.php/topic,123975.0.html#info_1024980

CUI exhibits the same behavior than DUI here. 
But DUI does https://github.com/reupen/columns_ui/issues/572 right. So I suppose it will be fixed, for consistency.

**Comment by reupen** [comment]
I assume you have a [Spanish keyboard](https://en.wikipedia.org/wiki/QWERTY#Spain) and mean Ctrl+Delete? 

Ctrl+Delete works everywhere I just tried, and I'm not doing anything special to handle it (Windows 10 22H2). What version of Windows are you using?

**Comment by regorxxx** [comment]
Ups, yep. Ctrl + Delete

Did you read the thread? It's deleting everything at right, not the next word.

**Comment by reupen** [comment]
I see the behaviour you describe on Windows 7, but not on Windows 10 22H2 or 11 22H2.

Window 10 1803 is quite old now, please update and try again.

**Comment by regorxxx** [comment]
Can't update the win 10 system. I don't see such behavior on any software (old and new) except foobar2000, on any of my win systems. 
Even tested it on win 7 and it works fine on other software. So I'm not really sure it's just a matter of updating (also the feature has been on win since win xp days...).

![ctrldel](https://user-images.githubusercontent.com/83307074/231971385-26d45152-817e-487e-b9b4-c96dcb62b823.gif)

![ctrldel2](https://user-images.githubusercontent.com/83307074/231972034-503019a8-3462-4093-96fa-550f2503beb2.gif)

**Comment by reupen** [comment]
The behaviour was changed in Windows 10 1809, seemingly [driven by a desire to improve the Registry Editor](https://learn.microsoft.com/en-us/windows/whats-new/ltsc/whats-new-windows-10-2019#registry-editor-improvements).

There's not much that it would make sense for Columns UI to do here. It's a standard Windows edit control, and Microsoft changed the behaviour of it at some point.

**Comment by regorxxx** [comment]
https://hydrogenaud.io/index.php/topic,123975.new.html#new

Will be fixed for DUI on next release. 

Don't agree with your reasoning though (for some of these win unwanted behaviors). There are a lot of systems out there, apart from win 11 (which has similar market share than win 7) and the last win 10 update, so doing nothing doesn't seem to me the right action. Also even if X unwanted behavior is how Win works, the UI is written over that base, so it's reasonable to expect fixes and improvements over it. Not just mimicking it.

As I showed, doing the same on Qbitorrent or notepad++ works. Yep, you can argue it doesn't use the standard edit control, but that means nothing for the final user, which only cares about this: Either it works as expected or not. 

Now DUI will work as expected and CUI not, which gives even more reasons to apply a fix.
