### ISSUE TITLE
White scrollbar in history panel

### ISSUE THREAD

**Issue by MuDevV** [reupen/columns_ui#701]
I'm discovering the dark theme and this is great.

My setup is very simple, with 3 views: the playlist of course, and in a sidebar (vertical splitter), playlists switcher and history, I use it since many years.

![2023-04-22 à 09 49 31](https://user-images.githubusercontent.com/125032349/233774003-adb990e1-cfd0-45ff-8803-d71397e43df4.png)

My "problem" is the scrollbar of the history panel is nearly white, while everything is dark in the window.

Is there a way to put this scrollbar dark, like the others?

Thanks

**Comment by reupen** [comment]
Hi,

Third-party components have to be updated to fully support dark mode (including scroll bar colours). If that component is no longer being maintained, and the source code is not available, then you are out of luck I'm afraid.

Thanks
