### ISSUE TITLE
Add search functionality to CUI playlist switcher when "custom title formating" uses a prefix before %title%.

### ISSUE THREAD

**Issue by Sneakpeakcss** [reupen/columns_ui#710]
https://github.com/reupen/columns_ui/issues/691

> Would it be possbile to somehow provide search functionality to CUI Playlist Switcher when a custom playlist title formating: ( prefix + %title%) is used ?

Currently creating any formatting for playlist switcher that has a prefix before %title% blocks the search functionality:

https://user-images.githubusercontent.com/77424331/236188060-dc554f73-5b17-4014-ada9-2e2e11ab4792.mp4

Technically it's somewhat possible to achieve this with a slightly _questionable_ workaround by creating a rule `$puts(invisSearch,$lower($cut(%title%,1)))` and use it as a invisible prefix with more _questionable_ color editing to hide it:

https://user-images.githubusercontent.com/77424331/236193880-bd25bb3d-62a4-4cef-bc0e-096a0095fe91.mp4

Unfortunately since `$set_font` isn't available in playlist switcher tittle formatting, this forces the user to use a monospaced font for the whole panel and is mostly limited to a single letter to avoid big empty space.

**Comment by reupen** [comment]
Thanks! It's difficult to imagine a scenario where someone would want to search based on the displayed text instead of the actual playlist name. So I'll probably just change the behaviour (so that it always uses the playlist name).
