### ISSUE TITLE
Playlist switcher and internet radio

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#718]
In Playlist switcher, duration (%length%) for internet radio playlist shows -0:29. Should be 0:00.

![Screenshot 2023-05-06 095610](https://user-images.githubusercontent.com/15456836/236611713-97f49c32-7da1-43a6-a98b-a88735480778.png)

**Comment by grimes2** [comment]
Solved it with 
`%title%' '$if(%is_playing%,🔉)
$tab()
$ifgreater(1,%length%,> 0:00,%length%)`

**Comment by reupen** [comment]
If it's showing a negative value, it's still a bug. It used to ignore these, it looks like it regressed when adding foobar2000 2.0 optimisations.
