### ISSUE TITLE
Return entire library when clearing Filter search without any Filter panels

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#720]
On clear search filter, playlist viewer is empty. Whole library should be showed in Filter results playlist (No filter).

**Comment by reupen** [comment]
Could you post a video showing what you mean? You can upload an MP4 or WebM file.

**Comment by grimes2** [comment]
Sure.

https://github.com/reupen/columns_ui/assets/15456836/5924a307-43bd-4520-a7e8-5e30052ab0a5

**Comment by reupen** [comment]
Okay, the behaviour depends on whether there are any Filter panels in the layout. The toolbar was intended to be used with Filter panels, but since it clearly works without them, it makes sense for the clear behaviour to be consistent in both cases. Thanks.
