### ISSUE TITLE
Suppress Default UI panel console warning in tab stack

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#722]
Add ability to suppress warning for Default UI elements .

> [16:36:39] Columns UI/Tab stack: Warning: ReFacets panel was visible on creation! This usually indicates a bug in this panel.

> [16:17:42] Columns UI/Tab stack: Warning: VU Meter panel was visible on creation! This usually indicates a bug in this panel.
> [16:17:42] Columns UI/Tab stack: Warning: Oscilloscope panel was visible on creation! This usually indicates a bug in this panel.
> [16:17:42] Columns UI/Tab stack: Warning: Peak Meter panel was visible on creation! This usually indicates a bug in this panel.
> [16:17:42] Columns UI/Tab stack: Warning: Spectrogram panel was visible on creation! This usually indicates a bug in this panel.
> [16:17:42] Columns UI/Tab stack: Warning: Spectrum panel was visible on creation! This usually indicates a bug in this panel.

**Comment by reupen** [comment]
It should be fixed in a future version of foobar2000. I'll leave this open until then.

**Comment by grimes2** [comment]
Fixed in foobar2000 v2.1 Preview 2023-05-22

>Fixed WS_VISIBLE bugs in Columns UI adapter (caused console warnings in some scenarios).
