### ISSUE TITLE
Jump to item in playlist view

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#726]
As I remember, it was possible to jump to a playlist item on keyboard input. This doesn't work anymore.

**Comment by Sneakpeakcss** [comment]
CUI only uses first column when searching in playlist, so you need to use a workaround (#355) and create an invisible 0 width column with `%title%` as "Display script", and place it in first position:

![image](https://github.com/reupen/columns_ui/assets/77424331/f16fae0a-1b05-4898-81da-affdabe344d8)

![image](https://github.com/reupen/columns_ui/assets/77424331/43bef883-aaed-4c08-a9b8-466f674d8bbe)

This also means that at this moment you're limited to searching with only one column that you choose (title,album,artist, etc)
