### ISSUE TITLE
Recent change crashes foobar when switching between Playlist view Columns

### ISSUE THREAD

**Issue by Sneakpeakcss** [reupen/columns_ui#739]
I'm not sure if you're interested in bug reports for unreleased versions, but it looks like changes in  [7c207f0](https://github.com/reupen/columns_ui/commit/7c207f00fa4653557ad250d416e3024a1b9cc378) (`c668866` being last working one) crash foobar while switching between columns, but only when `Options` tab is active while switching:

https://github.com/reupen/columns_ui/assets/77424331/887fdf5e-a768-4a30-b85b-5941767fa718

**Comment by reupen** [comment]
Thanks! Should be sorted by #740.

> I'm not sure if you're interested in bug reports for unreleased versions

Yes, absolutely. The earlier any bugs are picked up the better.
