### ISSUE TITLE
Add option to remove scrollbar

### ISSUE THREAD

**Issue by JohnnyFireOne** [reupen/columns_ui#745]
Please Add An Option To Remove Scrollbar

**Comment by reupen** [comment]
Which one? How are you going to scroll instead? It's very unlikely this would be implemented in any case.

**Comment by JohnnyFireOne** [comment]
> Which one? How are you going to scroll instead? It's very unlikely this would be implemented in any case.

everywhere we can scroll with the mouse instead! just make an option to enable and disable it please if you may!!!!!!!!!!

**Comment by JohnnyFireOne** [comment]
i will loved and will be so thrilled to see this in a new build!

**Comment by EzbyGT** [comment]
Me too. I would love to see this here as well as on your other project foo_uie_albumlist.

**Comment by JohnnyFireOne** [comment]
> Me too. I would love to see this here as well as on your other project foo_uie_albumlist.

lets hope this may happend in a nightly build for testing!
