### ISSUE TITLE
Allow separate sorting and display scripts for filters

### ISSUE THREAD

**Issue by calzonees** [reupen/columns_ui#796]
Unsure if this is feasible but this feature would vastly ease my use of CUI. Apologies if this has already been logged, I searched the issues but wording on some of them is unclear.

**Comment by reupen** [comment]
It would be helpful to give an example of what you mean/what you're trying to achieve.

There is https://github.com/reupen/columns_ui/issues/25 which is agree is a bit ambiguous as written... That came from https://hydrogenaud.io/index.php/topic,28647.msg917119.html#msg917119, so essentially it's being able to use fields like ARTIST SORT ORDER for ordering the items.

**Comment by calzonees** [comment]
Yes, that is what exactly what I'm talking about! My fault, I definitely saw that issue and didn't read the comments.
But yes, ignoring articles, as well as sorting by romanized artist names while displaying normally. I would also like to sort my filter for albums by DATE/FULLDATE while having it simply display the year.

Thanks for taking the time!

**Comment by reupen** [comment]
Okay, I've copied your last comment to the other issue and I'll close this one in favour of that one then. Feel free to add any other comments there (adding a reaction is not entirely unuseful as issues can be sorted by them...)

> Yes, that is what exactly what I'm talking about! My fault, I definitely saw that issue and didn't read the comments.

Don't worry, I only added that comment after replying here yesterday!
