### ISSUE TITLE
Add option to hide grouping label entirely if empty

### ISSUE THREAD

**Issue by guillochon** [reupen/columns_ui#831]
There are currently some "hacks" to achieve this using `$tab()`, but these hacks blank out the grouping entirely and leave an ugly space where it would be. My suggestion would be to add a checkbox to the grouping preferences that hides the grouping(s) entirely if they are empty. This would be a much cleaner look.

Current look when the secondary grouping is empty:

![image](https://github.com/reupen/columns_ui/assets/4998058/cf6287b1-7bd2-4478-94e8-8156e770f68b)

With `$tab()`, where you can see the extra space:

![image](https://github.com/reupen/columns_ui/assets/4998058/db134f4e-c9a3-49d7-aa70-02cae3360633)

And here's what it ought to look like if this feature was added:

![image](https://github.com/reupen/columns_ui/assets/4998058/b5a0ebff-5f2e-4c4d-90e8-bce310c19b30)

**Comment by guillochon** [comment]
Closing in favor of https://github.com/reupen/columns_ui/issues/386.

**Comment by josemescud** [comment]
I told music music about this problem more than 7 or 8 years ago. He replied that he thought it was logical and that he would take it into account for future versions. But until today he has not considered it and I have already lost hope.

For now I have solved it by ingenuity. 
1 - For the multiple albums I paint the line at the end of the name of the album and then I execute the grouping that paints the %discnumber%.

2- This makes that in the following disk that is not multiple it leaves me under the album a blank line. To avoid this what I have done is to remove the line after the album name and on the blank line I paint a line with the character ‾ to simulate a kind of underline $repeat('‾',$get(long_dash))

I also asked for each grouping to allow you to choose whether to paint on top of the cover or to the right of the cover. But I'm still waiting.

![2024-01-19](https://github.com/reupen/columns_ui/assets/50592876/db29dc30-796f-45e2-9b3f-3382014e8283)
