### ISSUE TITLE
High contrast selected text issue

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#837]
I'm not in the habit of using High Contrast themes at all but I was messing around and noticed this...

![image](https://github.com/reupen/columns_ui/assets/62050527/afca58ae-85b9-4a4c-97f5-4a115aa38fa8)

That's the playlist switcher on the left which has the same issue as the selected playlist item. Looks like both are using black text.

edit: that was 2.1.0 and I just tested the latest dev build from the actions page and it's the same there.

**Comment by reupen** [comment]
Thanks. It's probably using a colour from the theme when it shouldn't be. The system colour scheme is also broken, but in a different way...

**Comment by reupen** [comment]
On investigation, [theming has been used for high contrast themes since Windows 8](https://learn.microsoft.com/en-gb/windows/win32/controls/supporting-high-contrast-themes).

The problem is that the theme part in question is also drawing a background when a contrast theme is enabled. As the focus rectangle is currently drawn last, that background is being drawn on top of the text. Simply reordering the operations doesn't solve the problem, as you end up with the real background being rendered on top of the focus rectangle, or the focus rectangle background being rendered on top of the real background.

Setting a clipping region before drawing the focus rectangle so far is the most workable solution.

**Comment by marc2k3** [comment]
Thanks for looking in to it.

DUI playlist view does it right but the list control helpers in the SDK (libPPUI) get the text colour wrong. I reported the issue and a possible workaround here...

https://hydrogenaud.io/index.php/topic,125361.msg1038280

I know you don't touch ATL with a bargepole but maybe that RenderItem method gives some clues.

**Comment by reupen** [comment]
DUI doesn't use the theming API to draw the focus rectangle (so avoids the problem I described).

What Explorer is doing is a question but probably one that won't be answered...

**Comment by marc2k3** [comment]
Sorry I wasn't paying full attention. I blame the time of day. 😬

**Comment by reupen** [comment]
No worries, those were fair observations 🙂

To be honest, most weird theming-related list view issues arise because Explorer uses an old, undocumented technology called DirectUI for its list view. It has resulted in Explorer using the theming API in unconventional ways that are hard to replicate.

**Comment by marc2k3** [comment]
Using the most recent GH action build, this is not fixed on Windows 10, 19045.3930. Toolbar glitches when toggling are worse and the list controls are still not right - inactive filters seem OK but that was the case before. I didn't check those when making my original report.

![image](https://github.com/reupen/columns_ui/assets/62050527/537593fc-e610-430b-bd9f-58adf6411ba1)

![image](https://github.com/reupen/columns_ui/assets/62050527/2d804620-9aaf-4217-a05f-1d9627d66991)

![image](https://github.com/reupen/columns_ui/assets/62050527/6d0854da-90f2-4621-ae82-b933f42796e5)

Sorry for being a PITA over something I'm never really going to use. 😀

**Comment by reupen** [comment]
In a Windows 10 VM, I see some temporary glitching while the setting is being changed, but those are only temporary (unless I start interacting with foobar2000 while that is going on).

Is it foo_ui_columns-2.1.0+36.g28f5136.github.r7679344974.1128.x64.fb2k-component that you tested?

**Comment by reupen** [comment]
Just saw the version number in the second screenshot – that's an old one 😉

**Comment by marc2k3** [comment]
I'm so stupid it hurts. I think you should block me from posting on your repo. :grin:

**Comment by reupen** [comment]
Don't worry about it!
