### ISSUE TITLE
svg icons for Filter search

### ISSUE THREAD

**Issue by grimes2** [reupen/columns_ui#862]
svg icons for Filter search
![Screenshot 2024-03-01 015821](https://github.com/reupen/columns_ui/assets/15456836/3b875ce0-48a2-4680-9969-831c7f8d0b4e)

**Comment by reupen** [comment]
Do you mean the icons are blurry or jagged in your set-up? I just checked and SVGs are bundled and should be used if [SVG services](https://yuo.be/svg-services) is installed, and your set-up has an uncommon icon size (for which pre-rendered icons aren't included).

Do you have SVG services installed? What is the scale set to in Windows display settings?

**Comment by reupen** [comment]
Closing due to lack of detail.
