### ISSUE TITLE
Playlist switch scrollbar glitch

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#865]
If you have a playlist and select the last item like so, you can clearly see the scrollbar indicating I'm right at the end...

![image](https://github.com/reupen/columns_ui/assets/62050527/07f1908b-1733-4734-876c-5949283ee5dc)

But switch to another playlist and then back again, the content is still at the bottom but the scrollbar thinks it's at the top..

![image](https://github.com/reupen/columns_ui/assets/62050527/c694c687-60de-4639-b83e-62fa57930abb)

2.1.0 release

**Comment by reupen** [comment]
Reproduced, thanks. Surprised this hasn't been reported before – seems to be specifically when the other playlist doesn't have enough items for a scroll bar to appear.

**Comment by reupen** [comment]
Should be fixed – see if you can still break it in some way...

**Comment by marc2k3** [comment]
Looks good, thanks.
