### ISSUE TITLE
What does the Button item group set to None do?

### ISSUE THREAD

**Issue by stephen147** [reupen/columns_ui#887]
I tried to add [foo_run](https://www.foobar2000.org/components/view/foo_run) item like a PowerShell file to run a program but it appears that the **None** option here doesn't run the program.

Maybe this is not what it's meant to do?

I basically want to add a button that uses [foo_run](https://www.foobar2000.org/components/view/foo_run) to run a Powershell file without the need to have anything selected.

Here's the Powershell file on the foobar2000 thread.
https://hydrogenaud.io/index.php/topic,126007.msg1045173.html#msg1045173

![image](https://github.com/reupen/columns_ui/assets/14054664/22f37e3f-8895-489f-b4ee-8ac34dd38e0c)

**Comment by reupen** [comment]
It's a bit of an odd feature. It probably dates back to foobar2000 0.8.x when there wasn't much differentiation between main and context menu items internally.

It does try to do what you describe, but it ends up doing nothing as the SDK method used skips calling the context menu item if it's given no tracks. (That can be bypassed in theory.)

So, either that option should be removed or fixed.

**Comment by stephen147** [comment]
Okay, it would be nice for it to stay and run if there's nothing selected which is what I thought it was meant for.

If you can bypass it then great. Thanks.
