### ISSUE TITLE
Item properties / item details ignoring fromhook

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#903]
https://github.com/reupen/columns_ui/blob/e11232547d6bc5dd37707dfe9d75aadc04fb9642/foo_ui_columns/item_properties.cpp#L619

https://github.com/reupen/columns_ui/blob/e11232547d6bc5dd37707dfe9d75aadc04fb9642/foo_ui_columns/item_details.cpp#L511

Is there a reason for this? It means Playback Statistics / 3rd party components using metadb_index_manager::dispatch_refresh don't see real time updates.

If performance is an issue, maybe loosen it for handle counts of one?

**Comment by reupen** [comment]
Hmm, definitely wrong for Item details.

Taking the docs at face value, it looks correct for Item properties (as `p_fromhook` and `metadb_display_field_provider` are for title formatting). However, Selection Properties in DUI updates when changing ratings using Playback Statistics, so I assume Selection Proprieties is ignoring the flag (as I'm not sure how else it would be updating...)

**Comment by marc2k3** [comment]
> Hmm, definitely wrong for Item details.

IMHO, `Item properties` populating `Playback Statistics` / `Other` sections using `track_property_provider::enumerate` gets data from the exact the same place as `metadb_display_field_display` so it should respond to `on_changed_sorted` / `p_fromhook` as well.

**Comment by marc2k3** [comment]
Thanks for this.
