### ISSUE TITLE
DirectWrite Font Rendering - Character Descenders Clipped

### ISSUE THREAD

**Issue by JWatersMeet** [reupen/columns_ui#923]
The album art overlaps the descenders of characters in some scenarios, such as when they are used in grouping titles.
It may be that the height of the script calculation isn't taking these into account.
For example, in the screenshot below, the bottom of the 'g' is clipped.

![Screenshot 2024-07-25 153911](https://github.com/user-attachments/assets/a0ef4014-8e5e-4fad-88ba-c5e670d5365b)

**Comment by reupen** [comment]
Thanks, it was using the height of the items font rather than the group titles font. Should be resolved now.

**Comment by JWatersMeet** [comment]
That's fixed it, thank you!
