### ISSUE TITLE
DirectWrite list view header crash

### ISSUE THREAD

**Issue by marc2k3** [reupen/columns_ui#980]
[crash reports.zip](https://github.com/user-attachments/files/17115198/crash.reports.zip)

It appears the `index` here is invalid on startup...

https://github.com/reupen/ui_helpers/blob/7047d7ea1b8a9556dcab27a64ad2beef60fe408f/list_view/list_view_header.cpp#L129-L130

This seems to fix it locally but I wasn't confident enough to create PR. 😬 

```cpp
if (m_header_text_format && index < m_columns.size()) {
	const auto& column = m_columns[index];
```

**Comment by reupen** [comment]
Thanks. This old code can be a bit of a minefield 😞 Hopefully https://github.com/reupen/columns_ui/pull/981 sorts it.

**Comment by marc2k3** [comment]
Fixed, thanks. I just posted another related issue too.
